SELECT * FROM users;
SELECT * FROM localisations;
SELECT * FROM services;
SELECT * FROM plannings;
SELECT * FROM bookings;
SELECT * FROM blacklists;
SELECT * FROM logs;
SELECT * FROM messages;
SELECT * FROM avis;